image: node:latest

stages:
  - build
  - lint

cache:
  paths:
    - node_modules/

install_build:
  stage: build
  script:
    - npm install
    - npm run prod

code_lint:
  stage: lint
  script:
    - npm install
    - npm run lint
